# Generated by Django 4.2.3 on 2023-07-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hacker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=100, null=True)),
                ("lead_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lead_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "member1_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member2_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member3_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "member4_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
