# Generated by Django 4.2.3 on 2023-07-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='member3_name',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='member4_name',
        ),
    ]
