# Generated by Django 4.2.3 on 2023-07-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doubt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100)),
                ("doubt", models.CharField(max_length=1000)),
                ("recipient", models.CharField(max_length=100)),
                ("answer", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
