# Generated by Django 4.2.3 on 2023-07-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                ("theme", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "eligibility",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("team_size", models.CharField(blank=True, max_length=20, null=True)),
                ("prizes", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("website", models.URLField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
