# Generated by Django 4.2.3 on 2023-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organiser", "0002_alter_sponsor_description_alter_sponsor_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
