# Generated by Django 4.2.3 on 2023-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organiser", "0003_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
